
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff845b3bf4fde41deae34777b67eade52f9085c38988975b7351614e7d241a76995234891a123166b1038302eed53b7153890d27827a8b04b446d98db574c301

test:
  secret_key_base: b679f818635151877b26651b051bd8d91cbc784ed15c01dae7f8748d871f0fa68ce4e966d565f068b02aaee941adfb8eaed560aa5bf6dbbe28dcb65e7f865041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

